In [1]:
import pandas as pd

In [2]:
raw_data=pd.read_csv("Chrun Messy.csv")

In [3]:
df=pd.DataFrame(raw_data)

In [4]:
df.head()

,CustomerID,CustomerName,Gender,Age,City,State,PhoneNumber,Email,AccountType,Branch,...,NumProducts,LoanAmount_INR,FD_Amount_INR,HasCreditCard,IsActiveMember,MonthlyTransactions,ComplaintsLast12M,NetBankingEnabled,MobileBankingEnabled,Churn
0,CUST0078303,Neha Nair,1,NaN,Lucknow,Haryana,6526218743,neha.nair623@rediffmail.com,Salary,MG Road,...,1,200000,200000,0,1,68,0,1,1,0.0
1,CUST0066465,Akash Bhatt,MALE,24.0,Lucknow,West Bengal,6874264696,akash.bhatt909@yahoo.co.in,NRI,Civil Lines,...,1,200000,500000,0,0,76,3,1,1,1.0
2,CUST0093228,Kiran Bose,female,47.0,Jaipur,Madhya Pradesh,8386596852,kiran.bose446@yahoo.co.in,CURRENT,City Branch,...,2,500000,200000,0,1,10,0,1,1,0.0
3,CUST0001748,Meena Mishra,Male,69.0,Vadodara,Maharashtra,9304636996,meena.mishra923@gmail.com,Savings,Market Branch,...,1,1000000,0,1,1,96,1,0,1,0.0
4,CUST0080005,Shivam Pawar,1,72.0,Pune,Andhra Pradesh,8737069133,shivam.pawar692@yahoo.co.in,Salary,Civil Lines,...,1,100000,100000,1,0,32,0,1,1,0.0


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100500 entries, 0 to 100499
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   CustomerID            100500 non-null  object 
 1   CustomerName          100500 non-null  object 
 2   Gender                100500 non-null  object 
 3   Age                   98493 non-null   float64
 4   City                  100500 non-null  object 
 5   State                 100500 non-null  object 
 6   PhoneNumber           92467 non-null   object 
 7   Email                 92423 non-null   object 
 8   AccountType           100500 non-null  object 
 9   Branch                100500 non-null  object 
 10  DateOfJoining         95382 non-null   object 
 11  Occupation            99464 non-null   object 
 12  CreditScore           96482 non-null   float64
 13  TenureYears           100500 non-null  int64  
 14  AccountBalance_INR    97492 non-null   float64
 15  

In [6]:
df=df.dropna(subset="Churn")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   CustomerID            99491 non-null  object 
 1   CustomerName          99491 non-null  object 
 2   Gender                99491 non-null  object 
 3   Age                   97499 non-null  float64
 4   City                  99491 non-null  object 
 5   State                 99491 non-null  object 
 6   PhoneNumber           91532 non-null  object 
 7   Email                 91501 non-null  object 
 8   AccountType           99491 non-null  object 
 9   Branch                99491 non-null  object 
 10  DateOfJoining         94431 non-null  object 
 11  Occupation            98467 non-null  object 
 12  CreditScore           95522 non-null  float64
 13  TenureYears           99491 non-null  int64  
 14  AccountBalance_INR    96513 non-null  float64
 15  MonthlySalary_INR     9

In [8]:
df.drop("CustomerID",axis=1,inplace=True)
df.drop("CustomerName",axis=1,inplace=True)
df.drop("PhoneNumber",axis=1,inplace=True)
df.drop("Email",axis=1,inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Gender                99491 non-null  object 
 1   Age                   97499 non-null  float64
 2   City                  99491 non-null  object 
 3   State                 99491 non-null  object 
 4   AccountType           99491 non-null  object 
 5   Branch                99491 non-null  object 
 6   DateOfJoining         94431 non-null  object 
 7   Occupation            98467 non-null  object 
 8   CreditScore           95522 non-null  float64
 9   TenureYears           99491 non-null  int64  
 10  AccountBalance_INR    96513 non-null  float64
 11  MonthlySalary_INR     94531 non-null  float64
 12  NumProducts           99491 non-null  int64  
 13  LoanAmount_INR        99491 non-null  int64  
 14  FD_Amount_INR         99491 non-null  int64  
 15  HasCreditCard         9

In [10]:
df["Gender"].unique()

array(['1', 'MALE', 'female', 'Male', 'M', '0', 'F', 'FEMALE', 'male',
       'Female'], dtype=object)

In [11]:
gender_map ={
    "1" : "Male",
    "MALE" : "Male",
    "Male" : "Male",
    "M" : "Male",
    "male" : "Male",

    "female" : "Female",
    "0" : "Female",
    "F" : "Female",
    "FEMALE" : "Female",
    "Female" : "Female"
}

df["Gender"]=df["Gender"].map(gender_map)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Gender                99491 non-null  object 
 1   Age                   97499 non-null  float64
 2   City                  99491 non-null  object 
 3   State                 99491 non-null  object 
 4   AccountType           99491 non-null  object 
 5   Branch                99491 non-null  object 
 6   DateOfJoining         94431 non-null  object 
 7   Occupation            98467 non-null  object 
 8   CreditScore           95522 non-null  float64
 9   TenureYears           99491 non-null  int64  
 10  AccountBalance_INR    96513 non-null  float64
 11  MonthlySalary_INR     94531 non-null  float64
 12  NumProducts           99491 non-null  int64  
 13  LoanAmount_INR        99491 non-null  int64  
 14  FD_Amount_INR         99491 non-null  int64  
 15  HasCreditCard         9

In [13]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [14]:
df["Age"].min()

-1.0

In [15]:
df["Age"].max()

999.0

In [16]:
df.loc[df["Age"]<18 , "Age"]=None
df.loc[df["Age"]>100 , "Age"]=None

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Gender                99491 non-null  object 
 1   Age                   97349 non-null  float64
 2   City                  99491 non-null  object 
 3   State                 99491 non-null  object 
 4   AccountType           99491 non-null  object 
 5   Branch                99491 non-null  object 
 6   DateOfJoining         94431 non-null  object 
 7   Occupation            98467 non-null  object 
 8   CreditScore           95522 non-null  float64
 9   TenureYears           99491 non-null  int64  
 10  AccountBalance_INR    96513 non-null  float64
 11  MonthlySalary_INR     94531 non-null  float64
 12  NumProducts           99491 non-null  int64  
 13  LoanAmount_INR        99491 non-null  int64  
 14  FD_Amount_INR         99491 non-null  int64  
 15  HasCreditCard         9

In [18]:
df["City"].unique()

array(['Lucknow', 'Jaipur', 'Vadodara', 'Pune', 'Indore', 'Bangalore',
       'Kolkata', 'Delhi', 'Kochi', 'Nagpur', 'Noida', 'Thane',
       'Visakhapatnam', 'Hyderabad', 'Mysore', 'Ahmedabad', 'Patna',
       'Mumbai', 'Bhopal', 'Coimbatore', 'Gurgaon', 'Chandigarh', 'Surat',
       'Chennai'], dtype=object)

In [19]:
df["State"].unique()

array(['Haryana', 'West Bengal', 'Madhya Pradesh', 'Maharashtra',
       'Andhra Pradesh', 'Rajasthan', 'Gujarat', 'Telangana', 'Bihar',
       'Kerala', 'Tamil Nadu', 'Karnataka', 'Punjab', 'Uttar Pradesh',
       'Delhi'], dtype=object)

In [20]:
df["AccountType"].unique()

array(['Salary', 'NRI', 'CURRENT', 'Savings', 'savings', 'SAVINGS',
       'Current', 'current'], dtype=object)

In [21]:
acctype_map={
    "Salary" : "Salary",
    "NRI" : "NRI",
    "CURRENT" : "Current",
    "Current" : "Current",
    "current" : "Current",
    "Savings" : "Savings",
    "savings" : "Savings",
    "SAVINGS" : "Savings",
}

df["AccountType"]=df["AccountType"].map(acctype_map)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Gender                99491 non-null  object 
 1   Age                   97349 non-null  float64
 2   City                  99491 non-null  object 
 3   State                 99491 non-null  object 
 4   AccountType           99491 non-null  object 
 5   Branch                99491 non-null  object 
 6   DateOfJoining         94431 non-null  object 
 7   Occupation            98467 non-null  object 
 8   CreditScore           95522 non-null  float64
 9   TenureYears           99491 non-null  int64  
 10  AccountBalance_INR    96513 non-null  float64
 11  MonthlySalary_INR     94531 non-null  float64
 12  NumProducts           99491 non-null  int64  
 13  LoanAmount_INR        99491 non-null  int64  
 14  FD_Amount_INR         99491 non-null  int64  
 15  HasCreditCard         9

In [23]:
df["AccountType"].unique()

array(['Salary', 'NRI', 'Current', 'Savings'], dtype=object)

In [24]:
df["Branch"].unique()

array(['MG Road', 'Civil Lines', 'City Branch', 'Market Branch',
       'Sector 15', 'Andheri East', 'Koramangala', 'Electronic City',
       'Whitefield', 'Connaught Place', 'Main Branch', 'Bandra West'],
      dtype=object)

In [25]:
df["DateOfJoining"].sample(20)

25346     18/7/2017
21540      5/1/2021
17063     7/12/2008
72380     23/5/2024
93880     13/2/2007
6938       7/8/2019
70352     8/12/2018
50125     12/4/2016
63079     10/5/2010
95898     26/9/2024
31105     20/4/2019
35758     19/4/2011
73696    17-10-2024
39968     18/9/2005
8499      20/6/2015
68828    16/10/2005
50641     13/3/2010
12196    11/11/2011
82085     3/10/2017
94441      7/9/2018
Name: DateOfJoining, dtype: object

In [26]:
df["DateOfJoining"].astype(str).str.match(r"^\d{8}$").sum()

np.int64(2013)

In [27]:
mask = df["DateOfJoining"].astype(str).str.match(r"^\d{8}$")

df.loc[mask, "DateOfJoining"] = pd.to_datetime(
    df.loc[mask, "DateOfJoining"],
    format="%Y%m%d"
)

df["DateOfJoining"] = pd.to_datetime(
    df["DateOfJoining"],
    dayfirst=True,
    errors="coerce"
)

In [28]:
df["DateOfJoining"].isna().sum()

np.int64(9645)

In [29]:
df["DateOfJoining"].sample(20)

13134   2024-02-19
49755   2012-08-10
62710          NaT
12596   2006-04-23
90256          NaT
75094   2008-07-13
79385   2016-08-10
66785   2020-01-24
11375   2012-03-13
53853          NaT
90768   2016-06-09
27170   2006-08-06
82996          NaT
8806    2012-01-22
99270   2005-10-25
2889    2020-08-13
7870    2014-03-05
93056   2015-08-06
51681   2024-09-07
71107   2023-12-17
Name: DateOfJoining, dtype: datetime64[ns]

In [30]:
df["Occupation"].unique()

array(['Retired', 'Self-Employed', 'Business', 'Salaried', 'Homemaker',
       'Freelancer', 'Student', 'Government Employee', nan, 'Unknown'],
      dtype=object)

In [31]:
df["Occupation"]=df["Occupation"].fillna('Unknown')

In [32]:
df['Occupation'].unique()

array(['Retired', 'Self-Employed', 'Business', 'Salaried', 'Homemaker',
       'Freelancer', 'Student', 'Government Employee', 'Unknown'],
      dtype=object)

In [33]:
df["CreditScore"].min()

300.0

In [34]:
df["CreditScore"].max()

899.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Gender                99491 non-null  object        
 1   Age                   97349 non-null  float64       
 2   City                  99491 non-null  object        
 3   State                 99491 non-null  object        
 4   AccountType           99491 non-null  object        
 5   Branch                99491 non-null  object        
 6   DateOfJoining         89846 non-null  datetime64[ns]
 7   Occupation            99491 non-null  object        
 8   CreditScore           95522 non-null  float64       
 9   TenureYears           99491 non-null  int64         
 10  AccountBalance_INR    96513 non-null  float64       
 11  MonthlySalary_INR     94531 non-null  float64       
 12  NumProducts           99491 non-null  int64         
 13  LoanAmount_INR      

In [36]:
df["TenureYears"].min()

-1

In [37]:
df["TenureYears"].max()

19

In [38]:
df.loc[df["TenureYears"]<0,"TenureYears"]=None

In [39]:
df["TenureYears"].min()

0.0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Gender                99491 non-null  object        
 1   Age                   97349 non-null  float64       
 2   City                  99491 non-null  object        
 3   State                 99491 non-null  object        
 4   AccountType           99491 non-null  object        
 5   Branch                99491 non-null  object        
 6   DateOfJoining         89846 non-null  datetime64[ns]
 7   Occupation            99491 non-null  object        
 8   CreditScore           95522 non-null  float64       
 9   TenureYears           99391 non-null  float64       
 10  AccountBalance_INR    96513 non-null  float64       
 11  MonthlySalary_INR     94531 non-null  float64       
 12  NumProducts           99491 non-null  int64         
 13  LoanAmount_INR      

In [41]:
df.loc[df["AccountBalance_INR"]<0 , "AccountBalance_INR"]=None

In [42]:
df["AccountBalance_INR"].min()

0.0

In [43]:
df["AccountBalance_INR"].max()

999999999.0

In [44]:
df["MonthlySalary_INR"].min()

1234.0

In [45]:
df["MonthlySalary_INR"].max()

1533647.0

In [46]:
df["NumProducts"].min()

0

In [47]:
df["NumProducts"].max()

4

In [48]:
df["LoanAmount_INR"].min()

0

In [49]:
df["LoanAmount_INR"].max()

1000000

In [50]:
df["FD_Amount_INR"].min()

0

In [51]:
df["FD_Amount_INR"].max()

500000

In [52]:
df["HasCreditCard"].unique()

array([0, 1])

In [53]:
df["IsActiveMember"].unique()

array([1, 0])

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Gender                99491 non-null  object        
 1   Age                   97349 non-null  float64       
 2   City                  99491 non-null  object        
 3   State                 99491 non-null  object        
 4   AccountType           99491 non-null  object        
 5   Branch                99491 non-null  object        
 6   DateOfJoining         89846 non-null  datetime64[ns]
 7   Occupation            99491 non-null  object        
 8   CreditScore           95522 non-null  float64       
 9   TenureYears           99391 non-null  float64       
 10  AccountBalance_INR    96408 non-null  float64       
 11  MonthlySalary_INR     94531 non-null  float64       
 12  NumProducts           99491 non-null  int64         
 13  LoanAmount_INR      

In [55]:
df["MonthlyTransactions"].min()

0

In [56]:
df["MonthlyTransactions"].max()

99

In [57]:
df["ComplaintsLast12M"].min()

0

In [58]:
df["ComplaintsLast12M"].max()

5

In [59]:
df["NetBankingEnabled"].unique()

array([1, 0])

In [60]:
df["MobileBankingEnabled"].unique()

array([1, 0])

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99491 entries, 0 to 100499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Gender                99491 non-null  object        
 1   Age                   97349 non-null  float64       
 2   City                  99491 non-null  object        
 3   State                 99491 non-null  object        
 4   AccountType           99491 non-null  object        
 5   Branch                99491 non-null  object        
 6   DateOfJoining         89846 non-null  datetime64[ns]
 7   Occupation            99491 non-null  object        
 8   CreditScore           95522 non-null  float64       
 9   TenureYears           99391 non-null  float64       
 10  AccountBalance_INR    96408 non-null  float64       
 11  MonthlySalary_INR     94531 non-null  float64       
 12  NumProducts           99491 non-null  int64         
 13  LoanAmount_INR      

In [62]:
df.to_csv("Cleaned_data.csv",index=False)